### ISSUE TITLE
Javadoc and Images

### ISSUE THREAD

**Issue by lionelle** [CSU-CompSci-CS163-4/Lab03Conditionals#5]
Add javadoc to solution, generate and store in website, link to javadoc in lab. 

Add sample image (the one where we stay it is provided) to the public repository. Link in readme. Tag @lionelle  if help is needed with adding the link in the readme.

**Comment by silversun307** [comment]
Ok Lab03 should be done now, I updated the public and private repositories and added javadoc and image for laneCheck()
