### ISSUE TITLE
Final look-over

### ISSUE THREAD

**Issue by silversun307** [CSU-CompSci-CS163-4/Lab03Conditionals#6]
Lab03 should be done now, a last once-over would be appreciated for both this repository and the solution

**Comment by lionelle** [comment]
Looks good - to-fix: same issue on the transparent images:

![image](https://user-images.githubusercontent.com/8884669/147855514-7ef4322d-4f65-444f-a6c7-7c57dee0c43d.png)

**Comment by divy-s** [comment]
Looks great, but I am wondering if we should swap the placement of the Background Info and the Steps in the README as I feel some students will just try and hop into the steps before knowing how to follow them.

**Comment by silversun307** [comment]
Fixed the image in the readMe, still same issue with the extra image. I was thinking that some students will want to just get to the steps, or if they've read the info already won't want to have to scroll every time. Just my thoughts, I don't have a strong opinion on it
